export const PLANS = {
  light: {
    id: 'light',
    name: 'ライト',
    price: 2980,
    priceId: process.env.NEXT_PUBLIC_PRICE_LIGHT,
    mockPrice: 4980,
    mockPriceId: process.env.NEXT_PUBLIC_PRICE_MOCK_LIGHT,
    ichijoLimit: 10,
    reportLimit: 30,
    color: '#6366f1',
    features: [
      'レポート送信・AI分析',
      'スケジューラー9体',
      '一条剛チャット 月10回',
      'レポート保存 30件',
      '模試 ¥4,980/回',
    ],
  },
  standard: {
    id: 'standard',
    name: 'スタンダード',
    price: 4980,
    priceId: process.env.NEXT_PUBLIC_PRICE_STANDARD,
    mockPrice: 3980,
    mockPriceId: process.env.NEXT_PUBLIC_PRICE_MOCK_STANDARD,
    ichijoLimit: 30,
    reportLimit: 9999,
    color: '#8b5cf6',
    popular: true,
    features: [
      'レポート送信・AI分析',
      'スケジューラー9体',
      '一条剛チャット 月30回',
      'レポート保存 無制限',
      '模試 ¥3,980/回',
      '弱点論点抽出',
      '復習カード自動登録',
    ],
  },
  premium: {
    id: 'premium',
    name: 'プレミアム',
    price: 9800,
    priceId: process.env.NEXT_PUBLIC_PRICE_PREMIUM,
    mockPrice: 0,
    mockPriceId: null,
    ichijoLimit: 9999,
    reportLimit: 9999,
    color: '#f59e0b',
    features: [
      'レポート送信・AI分析',
      'スケジューラー9体',
      '一条剛チャット 無制限',
      'レポート保存 無制限',
      '本番レベルAI模試 毎月1回無料',
      '弱点論点抽出',
      '復習カード自動登録',
      '次月計画への自動反映',
      '成績分析ダッシュボード',
    ],
  },
}
